-- The primary key must uniquely identify each record.
-- A record's primary-key value can't be null.
-- The primary key-value must exist when the record is created.
-- The primary key must remain stable -- you can't change the primary-key field(s).
-- The primary key must be compact and contain the fewest possible attributes.
-- The primary-key value can't be changed.